ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENT_BOARD_NUM_FK FOREIGN KEY(COMMENT_BOARD_NUM) REFERENCES BOARD(BOARD_NUM) ON DELETE CASCADE;

SELECT BOARD_NUM, COMMENT_BOARD_NUM FROM BOARD LEFT OUTER JOIN COMMENTS ON BOARD_NUM = COMMENT_BOARD_NUM;

DELETE FROM(SELECT BOARD_NUM, COMMENT_BOARD_NUM FROM BOARD LEFT OUTER JOIN COMMENTS ON BOARD_NUM = COMMENT_BOARD_NUM WHERE BOARD_NUM = '88')BOARD WHERE BOARD_NUM ='88';

COMMIT;

ROLLBACK;

DELETE BOARD WHERE BOARD_NUM='87';

SELECT * FROM MEMBERT;
SELECT * FROM COMMENTS;
SELECT * FROM BOARD;

SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME='COMMENTS';

INSERT INTO BOARD VALUES ('ddd',SEQ_5TH.NEXTVAL,'FreeBoard','테스트2','제발',0,'',SYSDATE,'sss',0);
INSERT INTO BOARD VALUES ('ddd',SEQ_5TH.NEXTVAL,'FreeBoard','테스트3','제발',0,'',SYSDATE,'sss',0);
INSERT INTO BOARD VALUES ('ddd',SEQ_5TH.NEXTVAL,'FreeBoard','테스트4','제발',0,'',SYSDATE,'sss',0);
commit;

SELECT COUNT(*) FROM (SELECT BOARDLIST.*, ROW_NUMBER() OVER(ORDER BY BOARD_NUM DESC) AS RN FROM(SELECT * FROM BOARD WHERE BOARD_TITLE LIKE '%'||'테스트'||'%')BOARDLIST);

SELECT * FROM (SELECT BOARDLIST.*, ROW_NUMBER() OVER(ORDER BY BOARD_NUM DESC) AS RN FROM(SELECT * FROM BOARD WHERE BOARD_TITLE LIKE '%'||'테스트'||'%')BOARDLIST)WHERE RN BETWEEN 2 AND 5;
