SELECT * FROM USERINFO;

SELECT * FROM BOARDT;

SELECT * FROM BOARDT;

-- MYSQL,MSSQL 등에서는 AUTONUMBER 라고 불림
-- 게시판앞에 번호붙이기등에 활용가능
-- SEQUENCE(시퀀스) : 자동 순차 증가기능
-- 생성
-- CREATE SEQUENCE [SEQ_NAME] START WITH [시작값] INCREMENT BY [증가값];

-- 수정
-- ALTER SEQUENCE [SEQ_NAME] START WITH [시작값] INCREMENT BY [증가값]; 

-- 삭제
-- DROP SEQUENCE [SEQ_NAME];

CREATE SEQUENCE SEQ_DAN START WITH 1 INCREMENT BY 1;
SELECT SEQ_DAN FROM DUAL;
DROP SEQUENCE SEQ_DAN;
-- 증가
-- [SEQ_NAME].NEXTVAL;


-- 조회
-- SELECT [SEQ_NAME].CURRVAL FROM DUAL;
-- SELECT * FROM USER_SEQUENCE; 

-- 활용
CREATE SEQUENCE SEQ_DAN START WITH 1 INCREMENT BY 1;
-- 먼저 한번 값을 등록해야 조회가 가능하다.
SELECT SEQ_DAN.NEXTVAL FROM DUAL;
SELECT SEQ_DAN.CURRVAL FROM DUAL;
INSERT TEST(CL_NUM,TE_CODEMTE_NAME) VALUES (SEQ_DAN.NEXTVAL,'0000','아이언맨');

-- 응용을 하여 1~10으로 계속 반복되는 구문
-- 주의할점은 CYCLE의 기본값이 20이기 때문에 NOCACHE를 하여 싸이클값을 초기화가된다.
CREATE SEQUENCE SEQ_DAN START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 10 CYCLE NOCACHE;

SELECT * FROM BOARDT;

-- 가상테이블 (VIEW)
CREATE VIEW BOARDLIST AS 
SELECT BOARDT.*, ROW_NUMBER() OVER(ORDER BY BNUM DESC) AS RN
FROM BOARDT;

SELECT * FROM BOARDLIST;
SELECT * FROM BOARDT;

-- 1 페이지
SELECT * FROM BOARDLIST WHERE RN BETWEEN 1 AND 5;

-- 2 페이지
SELECT * FROM BOARDLIST WHERE RN BETWEEN 6 AND 10;


SELECT * FROM USERINFO;
SELECT * FROM BOARDT;
SELECT * FROM BOARDLIST;

SELECT * FROM BOARD_SY;
SELECT * FROM USERINFO_SY;
SELECT * FROM BOARDLIST_SY;

SELECT USERID, USERNAME, USERBIRTH, USERGENDER, USEREMAIL FROM USERINFO;

CREATE TABLE SEMIUSER(
USERID NVARCHAR2(10),
USERPASSWORD NVARCHAR2(15),
USERNAME NVARCHAR2(5),
USERLEVEL NUMBER(1),
USERADD NVARCHAR2(20),
USERPHONE NCHAR(13),
USERDATE DATE,
USERREGDATE DATE
)TABLESPACE USERS;

SELECT * FROM USERINFO;

ALTER TABLE SEMIUSER 
ADD CONSTRAINT USERID_PK PRIMARY KEY(USERID);

ALTER TABLE SEMIUSER 
MODIFY USERREGDATE DEFAULT SYSDATE;


SELECT COUNT(USERID) FROM SEMIUSER WHERE USERID='0000';

ALTER TABLE SEMIUSER 
MODIFY USERPASSWORD NOT NULL;

ALTER TABLE SEMIUSER 
MODIFY USERLEVEL DEFAULT 1;

SELECT BOARDJHI.*, ROW_NUMBER() OVER(ORDER BY NUMS DESC) AS NUMSSFROM BOARDJHI;
COMMIT;
INSERT INTO USERINFO_SY VALUES('?','?','?',SYSDATE,'?','?');